import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";
import Login from "../components/login";

export default function Home({ data }) {
    if (data == null) return <Login />;
    else
        return (
            <div className="bg-gray-200 h-screen">
                <Head>
                    <title>Nitish's FB Project</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Header />
            </div>
        );
}

export async function getServerSideProps(context) {
    const session = await getSession(context);
    const data = session;
    return {
        props: { data },
    };
}
