import { unstable_getServerSession } from "next-auth";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";
import Login from "../components/login";
import { authOptions } from "./api/auth/[...nextauth]";

export default function Home() {
    const { data: session } = useSession();
    console.log(session);
    if (session == null) return <Login />;
    else
        return (
            <div className="bg-gray-200 h-screen">
                <Head>
                    <title>Nitish - FB Project</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Header />
            </div>
        );
}

export async function getServerSideProps(context) {
    const session = await getSession(context);
    // const session = await unstable_getServerSession(
    //     context.req,
    //     context.res,
    //     authOptions
    // );

    console.log(session);
    return {
        props: { session: session },
    };
}
